#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace(path: str, old: str, new: str) -> None:
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"missing expected text in {path}: {old[:90]!r}")
    text = text.replace(old, new, 1)
    p.write_text(text, encoding="utf-8")


# Release marker: copy-only release, R96 visual system remains unchanged.
for path in (
    "keeper.html", "index.html", "solutions.html",
    "en/keeper.html", "en/index.html", "en/solutions.html",
    "de/keeper.html", "de/index.html", "de/solutions.html",
):
    replace(path, '<meta content="R96" name="axiona-release"/>', '<meta content="R97" name="axiona-release"/>')

# Hungarian Keeper — remove robotic/product-internal wording and duplicate concepts.
hu = "keeper.html"
replace(hu, "Behozod az iratot. A Keeper elvégzi körülötte az adminisztráció nagy részét.", "Behozod az iratot. A Keeper elvégzi a vele járó adminisztráció nagy részét.")
replace(hu, "PDF, kép vagy fotó érkezik. A Keeper elolvassa, megpróbálja felismerni, miről van szó, röviden összefoglalja, kiemeli a fontos adatokat és dátumokat, majd javasolja, hová tartozik és van-e vele teendőd. Neked nem kell minden fájlt külön végigolvasni, elnevezni, besorolni és észben tartani.", "Legyen az PDF vagy egy iratról készült kép, a Keeper elolvassa, megpróbálja felismerni, mi az, röviden összefoglalja, kiemeli a fontos adatokat és dátumokat, majd megmutatja, mihez tartozhat és kell-e vele foglalkoznod. Nem neked kell minden dokumentumot külön végigolvasni, elnevezni, besorolni és fejben tartani.")
replace(hu, "Ha valami bizonytalan, a Keeper ezt jelzi, és te javíthatod. Emlékeztető vagy más következő lépés csak a jóváhagyásoddal készül.", "Ha valamiben nem biztos, azt jelzi. Te javíthatod, és emlékeztető vagy más teendő csak akkor készül, ha jóváhagyod.")
replace(hu, "Szöveggé alakítja és feldolgozza.", "Elolvassa a dokumentumot.")
replace(hu, "Nem csak a fájlnevet látja: a dokumentum tartalma lesz az alap.", "A tartalmával dolgozik, nem csak a fájlnévvel.")
replace(hu, "Megpróbálja felismerni, milyen irat érkezett.", "Megpróbálja felismerni, mi érkezett.")
replace(hu, "Röviden összefoglalja, miről szól, és kiemeli, ami fontos.", "Összefoglalja és kiemeli a lényeget.")
replace(hu, "Dátum, összeg, azonosító, kibocsátó vagy határidő — és megmutathatja azt is, honnan olvasta ki.", "Dátum, összeg, azonosító, kibocsátó vagy határidő — és ahol lehet, azt is megmutatja, honnan vette az adatot.")
replace(hu, "Javasolja a kategóriát és a kapcsolatokat.", "Megkeresi, mihez tartozhat.")
replace(hu, "Mihez, kihez vagy melyik ügyhöz tartozhat az irat; a bizonytalan kapcsolat visszakérdezhető.", "Javasolhat kapcsolatot személyhez, szolgáltatóhoz, szerződéshez, eszközhöz vagy egy ügyhöz. Ha nem biztos benne, rákérdezhet.")
replace(hu, "Megmutatja, ha valami figyelmet kér.", "Szól, ha érdemes foglalkoznod vele.")
replace(hu, "Lehetséges határidő, ellenőrizendő adat vagy következő teendő.", "Például ha határidőt, bizonytalan adatot vagy lehetséges következő lépést talál.")
replace(hu, "A Keeper előkészít és javasol, de a fontos lépéseket nem végzi el helyetted.", "A Keeper segít előkészíteni a következő lépést, de nem dönt helyetted.")
replace(hu, "Amit ellenőrizni kell, azt megmutatja. Emlékeztető vagy más teendő csak a jóváhagyásoddal készül.", "A bizonytalan részeket te ellenőrzöd. Emlékeztető vagy más teendő csak a jóváhagyásoddal készül.")
replace(hu, "Nem az a lényeg, hogy megvan a fájl. Hanem hogy értsd is, mi van benne.", "Nem elég, hogy megvan az irat. Jó lenne rögtön tudni, mi van benne és mi a dolgod vele.")
replace(hu, "Egy digitális irattár elteszi a dokumentumot. A valódi adminisztráció viszont ezután kezdődik: meg kell érteni, mi érkezett, ki kell szedni belőle a fontos adatot, el kell dönteni, mihez tartozik, és észben kell tartani, ha tenni kell valamit. A Keeper célja, hogy ennek a kézi munkának a nagy részét levegye rólad.", "Egy tárhely megőrzi a fájlt. De attól még neked kell elolvasni, kiszedni belőle a fontos adatokat, kitalálni, mihez tartozik, és észben tartani a határidőket. A Keeper pont ebből a munkából vesz le minél többet.")
replace(hu, "<h3>Mi ez?</h3><p>Megpróbálja felismerni, hogy például számla, szerződés, értesítő vagy levél érkezett.</p>", "<h3>Mi ez az irat?</h3><p>Megpróbálja felismerni, hogy például számla, szerződés, értesítő vagy levél érkezett.</p>")
replace(hu, "<h3>Miről szól, és mi fontos benne?</h3><p>Röviden összefoglalja, kiemeli a lényeges adatokat és dátumokat, és megmutathatja, melyik részből olvasta ki őket.</p>", "<h3>Mi fontos benne?</h3><p>Röviden összefoglalja, miről szól, kiemeli a lényeges adatokat és dátumokat, és ahol lehet, megmutatja, melyik részből vette őket.</p>")
replace(hu, "Megkeresi, melyik személyhez, szolgáltatóhoz, szerződéshez, eszközhöz vagy ügyhöz kapcsolódhat.", "Megnézi, melyik személyhez, szolgáltatóhoz, szerződéshez, eszközhöz vagy ügyhöz kapcsolódhat.")
replace(hu, "<h3>Kell vele valamit tennem?</h3><p>Ha az iratban határidő vagy tennivaló van, külön jelzi, és javaslatot tehet a következő lépésre.</p>", "<h3>Van vele dolgom?</h3><p>Ha határidőt vagy tennivalót talál, külön jelzi, és javasolhat egy következő lépést.</p>")
replace(hu, "Te behozod. A feldolgozás nagy részét a Keeper végzi.", "Te behozod az iratot. A Keeper végigmegy rajta.")
replace(hu, "A tervezett felhasználói út nem mappák építésével kezdődik. Egy dokumentummal kezdődik, amelyből a Keeper lépésről lépésre használható adminisztrációs információt készít.", "Nem kell előre kitalálnod, hová mentsd vagy hogyan nevezd el. Elég behozni az iratot; a Keeper lépésről lépésre feldolgozza.")
replace(hu, "PDF, kép, fotó vagy megosztott irat.", "PDF vagy egy iratról készült kép.")
replace(hu, "02 / HELYI OCR", "02 / SZÖVEGFELISMERÉS")
replace(hu, "A szöveget helyben kinyeri, így a további feldolgozás nem pusztán a fájlnévre támaszkodik.", "A szöveget lehetőleg a készüléken olvassa ki, így később nem csak a fájlnévből kell dolgoznia.")
replace(hu, "03 / MEGÉRTÉS", "03 / ÉRTELMEZÉS")
replace(hu, "Megérti, mi érkezett.", "Megpróbálja megérteni, milyen iratról van szó.")
replace(hu, "Rövid, közérthető összefoglalót készíthet, és javaslatot adhat a dokumentum típusára és kategóriájára. Ha valami bizonytalan, ellenőrzésre hagyja.", "Készíthet rövid összefoglalót, és javaslatot adhat arra, milyen dokumentumról van szó. Ha valamiben nem biztos, azt jelzi.")
replace(hu, "KEEPER: MEGÉRTI ÉS ÖSSZEFOGLALJA", "KEEPER: ÉRTELMEZI ÉS ÖSSZEFOGLALJA")
replace(hu, "Kiemeli, ami számít.", "Kiemeli, amit érdemes észrevenni.")
replace(hu, "Dátumok, határidők, összegek és más lényeges értékek külön megjelenhetnek, az eredeti forrás visszanézhető.", "Dátumok, határidők, összegek és más fontos adatok külön megjelenhetnek. Az eredeti irat bármikor visszanézhető.")
replace(hu, "KEEPER: KIEMELI ÉS MEGMUTATJA A FORRÁST", "KEEPER: KIEMELI A FONTOS ADATOKAT")
replace(hu, "Javasolja a helyét és a kapcsolatait.", "Megkeresi a helyét a többi irat között.")
replace(hu, "A cél nem egyetlen merev mappa, hanem annak felismerése, hogy az irat mihez, kihez vagy melyik ügyhöz tartozik. Az automatikus javaslat javítható és visszafordítható.", "Javasolhat kategóriát és kapcsolatot ahhoz a személyhez, szolgáltatóhoz, szerződéshez, eszközhöz vagy ügyhöz, amihez az irat tartozik. A javaslatot bármikor javíthatod.")
replace(hu, "KEEPER: BESOROLÁST ÉS KAPCSOLATOT JAVASOL", "KEEPER: MEGKERESI, MIHEZ TARTOZHAT")
replace(hu, "Szól, ha dolgod lehet vele.", "Szól, ha valami következik.")
replace(hu, "Határidő, várakozás vagy teendő esetén javaslat jelenhet meg. Emlékeztető csak a jóváhagyásod után készül.", "Ha határidőt vagy tennivalót talál, jelzi. Emlékeztető csak akkor készül, ha jóváhagyod.")
replace(hu, "Nem a tárolás a termék lényege.", "Több annál, mint hogy elteszi a fájlokat.")
replace(hu, "A fájl megőrzése csak az alap. A Keeper értéke ott kezdődik, amikor a dokumentumból érthető, kereshető és használható ügyintézési információ lesz.", "A tárolás csak az első lépés. A Keeper attól lesz hasznos, hogy segít értelmezni az iratot, összekötni azzal, amihez tartozik, és észrevenni, ha teendőd van vele.")
replace(hu, "KEEPER FEJLESZTÉSI IRÁNY", "KEEPER")
replace(hu, "Megőrzi a fájlt.", "Elteszi a fájlt.")
replace(hu, "A dokumentum ott van, de továbbra is neked kell elolvasni és értelmezni.", "Megvan, de továbbra is neked kell elolvasni és értelmezni.")
replace(hu, "Feldolgozza a tartalmát.", "Elolvassa és kiemeli a lényeget.")
replace(hu, "Felismerési és adatkinyerési javaslatot készít, hogy ne nulláról indulj.", "Nem egy ismeretlen fájlból kell elindulnod: a fontos részek már előkerülhetnek.")
replace(hu, "Jelentést és kapcsolatot ad a dokumentumnak.", "Segít megmutatni, mihez tartozik.")
replace(hu, "Típus, kategória, kapcsolódó személy, szerződés, eszköz vagy ügy lehet a kontextus.", "Javasolhat kategóriát, és összekötheti az iratot a kapcsolódó személlyel, szerződéssel, eszközzel vagy üggyel.")
replace(hu, "A fontos dátum bent marad a PDF-ben.", "A határidő bent marad a dokumentumban.")
replace(hu, "Kiemeli a lehetséges határidőt.", "Kiemelheti a határidőt.")
replace(hu, "A forrás visszanézhető, és emlékeztető csak jóváhagyás után készül.", "Az eredeti rész visszanézhető, emlékeztető pedig csak a jóváhagyásoddal készül.")
replace(hu, "Keresel egy fájlt.", "Neked kell emlékezned, hol keresd.")
replace(hu, "Fájlnévre, helyre vagy saját emlékezetre támaszkodsz.", "Fájlnévre, mappára vagy arra hagyatkozol, hogy emlékszel, hová tetted.")
replace(hu, "A dokumentum tartalma is kereshetővé válik.", "A tartalmában is kereshetsz.")
replace(hu, "A cél, hogy később ne azt kelljen felidézni, hová mentetted.", "Így később nem feltétlenül kell tudnod, milyen néven vagy hová mentetted.")
replace(hu, "Ugyanaz a Keeper-munka, egészen különböző iratoknál.", "Ugyanaz a segítség, egészen különböző iratoknál.")
replace(hu, "Az alábbiak a tervezett termékműködés szemléltető példái. Nem kész felhasználói adatok és nem automatikus döntések.", "Néhány hétköznapi példa arra, milyen munkát vehet le rólad a Keeper.")
replace(hu, "Ne neked kelljen kibányászni az ügyszámot és a határidőt.", "Ne neked kelljen megkeresni az ügyszámot és a határidőt.")
replace(hu, "Beérkezik egy levél a biztosítótól. A dokumentum önmagában még csak egy PDF.", "Beérkezik egy biztosítói levél. A Keeper segíthet rögtön elővenni belőle azt, ami az ügyintézéshez kell.")
replace(hu, "felismeri a dokumentum jellegét", "felismeri, hogy biztosítói irat lehet")
replace(hu, "javasolja a kapcsolódó kárügyet vagy járművet", "megkeresi, melyik kárügyhöz vagy járműhöz kapcsolódhat")
replace(hu, "jelzi, ha válasz vagy követés lehet szükséges", "jelzi, ha válaszolni vagy később utánanézni kell")
replace(hu, "A határidő ne csak egy sor legyen a dokumentumban.", "A fizetési határidő ne vesszen el a sorok között.")
replace(hu, "A Keeper a dokumentumból strukturált, ellenőrizhető adatot próbál készíteni.", "Egy számlánál nem csak az számít, hogy megvan, hanem az is, mennyi, mikorra és ki állította ki.")
replace(hu, "kibocsátó, összeg és dátum javasolt felismerése", "kiemeli a kibocsátót, az összeget és a dátumot")
replace(hu, "dokumentumtípus és kategória javaslata", "felismeri, hogy számla vagy fizetési értesítő lehet")
replace(hu, "határidő forrásának megmutatása", "megmutatja, hol szerepel a határidő")
replace(hu, "emlékeztető-javaslat, amelyet te hagysz jóvá", "emlékeztetőt javasolhat, amit te hagysz jóvá")
replace(hu, "Ne neked kelljen fejben összekötni a régi és az új iratokat.", "Az új irat találja meg a régi szerződést, ne neked kelljen emlékezned rá.")
replace(hu, "kapcsolatot javasol a korábbi iratokhoz", "megkeresi, mely korábbi iratokhoz kapcsolódhat")
replace(hu, "Sok különböző iratból egy érthető adminisztrációs kép.", "Sokféle irat, mégis ugyanahhoz a munkához tartoznak.")
replace(hu, "javasolja a közös projekt- vagy ügykapcsolatot", "megkeresi, melyik munkához vagy ügyhöz tartozhatnak")
replace(hu, "segít később ugyanabból a kontextusból folytatni", "segít később ott folytatni, ahol abbahagytad")
replace(hu, "A Keeper segít. Nem dönt helyetted.", "A Keeper segít, de a végső szó a tiéd.")
replace(hu, "A fontos adatnak legyen forrása.", "Lásd, honnan jött egy fontos adat.")
replace(hu, "A cél, hogy lásd, melyik rész alapján került elő egy dátum vagy más fontos érték.", "Egy fontos dátumnál vagy összegnél vissza tudd nézni azt a részt, ahonnan a Keeper kiolvasta.")
replace(hu, "A bizonytalanság látszódjon.", "Ha nem biztos benne, mondja meg.")
replace(hu, "Ha valami nem biztos, a Keeper ne tegyen úgy, mintha az lenne. Ellenőrzést kérhet.", "Ha valamit nem tud elég biztosan felismerni, jelezze, hogy érdemes ellenőrizned.")
replace(hu, "A te javításod az első.", "Ha kijavítod, azt tartsa tiszteletben.")
replace(hu, "A felhasználói korrekciót a rendszer nem írhatja felül csendben egy későbbi automatikus javaslattal.", "A te javításodat később se írja át észrevétlenül egy automatikus javaslat.")
replace(hu, "Az AXIONA Keeper fejlesztés alatt áll, jelenleg nem tölthető le. Az első tervezett nyilvános kiadás az Apple App Store-ban jelenik meg. A weboldal a termék célját és tervezett működését mutatja; nem kész alkalmazásként mutatja be.", "Az AXIONA Keeper fejlesztés alatt áll, még nem tölthető le. Az első nyilvános kiadást iPhone-ra és iPadre tervezzük, az Apple App Store-on keresztül.")
replace(hu, "Ha valaki sok irattal, határidővel és hétköznapi ügyintézéssel küzd, innen közvetlenül továbbküldheted a Keeper bemutatóját.", "Ismersz valakit, akinek sok ideje megy el iratokra, határidőkre és ügyintézésre? Innen egyszerűen továbbküldheted neki a Keeper bemutatóját.")

# Hungarian overview and Solutions — concise, benefit-first, no duplicate image/photo wording.
replace("index.html", "Nem neked kell minden iratot kibogarászni és kézzel elrendezni.", "Ne az iratok rendezése vigye el az idődet.")
replace("index.html", "Behozol egy PDF-et, képet vagy fotót. A Keeper célja, hogy elolvassa, felismerje, milyen iratról van szó, kiemelje a fontos adatokat, segítsen besorolni és összekapcsolni azzal, amihez tartozik, majd jelezze, ha valami figyelmet kér. A fontos döntés nálad marad.", "Behozol egy PDF-et vagy egy iratról készült képet. A Keeper elolvassa, megpróbálja felismerni, mi az, kiemeli a fontos adatokat, megkeresi, mihez tartozhat, és szól, ha dolgod lehet vele. A döntés nálad marad.")
replace("index.html", "Felismeri és kiemeli.", "Megérti és kiemeli.")
replace("index.html", "Dokumentumtípus, fontos adatok, dátumok és lehetséges határidők.", "Röviden összefoglalja, és előveszi a fontos adatokat, dátumokat, határidőket.")
replace("index.html", "Rendbe teszi.", "Megkeresi, mihez tartozik.")
replace("index.html", "Kategóriát és kapcsolatot javasol ahhoz, amihez az irat tartozik.", "Kapcsolatot javasol a megfelelő személyhez, szerződéshez, eszközhöz vagy ügyhöz.")
replace("index.html", "Jelzi, ha dolgod lehet vele.", "Szól, ha dolgod van vele.")
replace("index.html", "A következő lépés javaslat marad; te ellenőrzöd és hagyod jóvá.", "Ha teendőt vagy határidőt talál, jelzi. A következő lépést te hagyod jóvá.")
replace("index.html", "Kevesebb kézi adminisztráció. Kevesebb bizonytalanság.", "Kevesebb keresgélés. Kevesebb kézi adminisztráció.")
replace("solutions.html", "Privát dokumentum-asszisztens, amely nem csak megőrzi az iratot, hanem segít megérteni és elrendezni.", "Privát dokumentum-asszisztens, amely nem csak elteszi az iratot: segít megérteni, mi van benne, mihez tartozik és van-e vele teendő.")
replace("solutions.html", "Behozod az iratot. A Keeper dolgozik rajta.", "Behozod az iratot. A Keeper végigmegy rajta.")
replace("solutions.html", "A cél: elolvasni a dokumentumot, felismerni a típusát, kiemelni a fontos adatokat és határidőket, javasolni a megfelelő kategóriát és kapcsolatot, majd megmutatni, ha teendő van vele. Nem egyszerű tárhely, hanem a kézi adminisztráció csökkentésére épülő rendszer.", "Elolvassa, megpróbálja felismerni, mi az, kiemeli a fontos adatokat és határidőket, megkeresi, mihez tartozhat, és szól, ha valamit intézned kell. A cél egyszerű: kevesebb idő menjen el az iratok kézi rendezésére és újraolvasására.")
replace("solutions.html", "helyi OCR-rel feldolgozza a tartalmat", "a dokumentum tartalmával dolgozik")
replace("solutions.html", "dokumentumtípus- és kategóriajavaslat", "megpróbálja felismerni, milyen irat")
replace("solutions.html", "kapcsolatot és kontextust javasol", "megkeresi, mihez tartozhat")
replace("solutions.html", "ha valami ellenőrzést vagy teendőt kér", "ha ellenőrizni vagy intézni kell valamit")
replace("solutions.html", "A fontos lépéseket te hagyod jóvá.", "A döntés nálad marad.")

# English Keeper — native, product-human copy; remove AI/product-team phrasing.
en = "en/keeper.html"
replace(en, "Bring in the document. Keeper does most of the admin work around it.", "Bring in the document. Keeper takes care of much of the admin around it.")
replace(en, "A PDF, image or photo comes in. Keeper is designed to read it, work out what it may be, summarize it, surface important facts and dates, then suggest where it belongs and whether it needs your attention. You should not have to read, name, classify and remember every file by hand before it becomes useful.", "Whether it is a PDF or a photo of a document, Keeper reads it, tries to understand what it is, gives you a short summary, pulls out important facts and dates, then shows what it may belong to and whether you need to do anything with it. You should not have to read, name, sort and remember every document by hand.")
replace(en, "Keeper proposes and prepares. You can review uncertain information, and anything with a real-world consequence remains under your approval.", "If Keeper is not sure about something, it tells you. You can correct it, and reminders or other next steps only happen after you approve them.")
replace(en, "Turn the document into usable text.", "Read the document.")
replace(en, "The content, not just the filename, becomes the basis for what happens next.", "Keeper works from the content, not just the filename.")
replace(en, "Suggest what kind of document arrived.", "Try to recognize what arrived.")
replace(en, "Surface what may matter for the admin task.", "Summarize it and pull out what matters.")
replace(en, "Dates, amounts, references, issuer and deadlines where the source supports them.", "Dates, amounts, reference numbers, sender and deadlines — and, where possible, the part of the document they came from.")
replace(en, "Suggest category and context.", "Work out what it may belong to.")
replace(en, "What person, provider, contract, asset or matter the document may belong to; ambiguous links stay reviewable.", "It can suggest a link to the right person, provider, contract, asset or matter. If the match is uncertain, you can review it.")
replace(en, "Show when something may need attention.", "Tell you when something may need your attention.")
replace(en, "A possible deadline, uncertain fact or next action.", "For example, a deadline, something worth checking or a possible next step.")
replace(en, "Keeper does not quietly execute consequential actions for you.", "Keeper can prepare the next step, but it does not decide for you.")
replace(en, "Reminders and other practical actions require review and approval.", "You review uncertain details, and reminders or other actions only happen after you approve them.")
replace(en, "Having the file is not enough. You still need to understand what it means.", "Having the document is not enough. You also need to know what is in it and what to do with it.")
replace(en, "A digital archive can store a document. The admin work starts after that: understand what arrived, pick out the important facts, decide what it belongs to and remember whether something needs to happen. Keeper is designed to remove as much of that manual work as possible.", "Storage keeps the file. You still have to read it, find the important details, work out what it belongs to and remember the deadlines. Keeper is designed to take as much of that work off your hands as possible.")
replace(en, "Keeper can propose a document type so you do not have to infer it from a filename.", "Keeper tries to recognize whether it is, for example, an invoice, contract, notice or letter.")
replace(en, "Important facts and dates can be surfaced, with source evidence behind important values.", "It summarizes the document, pulls out important facts and dates and, where possible, shows where they came from.")
replace(en, "Keeper can suggest category and relationships to a person, provider, contract, asset or matter.", "It can suggest which person, provider, contract, asset or matter the document belongs to.")
replace(en, "If a deadline or next step is detected, Keeper can flag it separately and propose an action.", "If it finds a deadline or something you may need to do, it brings that to your attention.")
replace(en, "You bring the document in. Keeper does most of the processing.", "You bring in the document. Keeper works through it.")
replace(en, "The intended user journey does not begin with building folders. It begins with a document, which Keeper gradually turns into useful, reviewable administrative information.", "You do not need to decide on folders or filenames first. Bring in the document and Keeper works through it step by step.")
replace(en, "PDF, image, photo or shared document.", "PDF or a photo of a document.")
replace(en, "02 / LOCAL OCR", "02 / TEXT RECOGNITION")
replace(en, "Text is extracted locally so later processing can work from document content rather than filename alone.", "Where possible, Keeper reads the text on your device so it can work from the document itself, not just its filename.")
replace(en, "03 / UNDERSTAND", "03 / MAKE SENSE OF IT")
replace(en, "Understand what arrived.", "Work out what kind of document it may be.")
replace(en, "Keeper can prepare a short plain-language summary and suggest the document type and category. Uncertain results stay open for review.", "Keeper can give you a short summary and suggest what kind of document it is. If it is not sure, it says so.")
replace(en, "KEEPER: UNDERSTANDS AND SUMMARIZES", "KEEPER: MAKES SENSE OF IT AND SUMMARIZES")
replace(en, "Surface what matters.", "Pull out what is worth noticing.")
replace(en, "Dates, deadlines, amounts and other useful values can be presented separately, with the original source available for review.", "Dates, deadlines, amounts and other important details can be shown separately. You can always go back to the original document.")
replace(en, "KEEPER: SURFACES FACTS AND SOURCE", "KEEPER: PULLS OUT IMPORTANT DETAILS")
replace(en, "Suggest where it belongs and what it relates to.", "Find where it fits with your other documents.")
replace(en, "The goal is not one rigid folder tree. It is to understand what person, provider, contract, asset or matter gives the document context. Automatic proposals remain editable and reversible.", "Keeper can suggest a category and a link to the person, provider, contract, asset or matter the document belongs to. You can correct the suggestion at any time.")
replace(en, "KEEPER: SUGGESTS CLASSIFICATION AND CONTEXT", "KEEPER: FINDS WHAT IT MAY BELONG TO")
replace(en, "Flag when it may need your attention.", "Tell you when something comes next.")
replace(en, "A deadline, waiting state or action can become a proposal. A reminder is created only after you approve it.", "If Keeper finds a deadline or something you may need to do, it tells you. A reminder is only created after you approve it.")
replace(en, "Storage is not the product.", "It does more than store files.")
replace(en, "Keeping the file is only the foundation. Keeper becomes useful when a document turns into understandable, searchable and actionable administrative information.", "Storage is only the first step. Keeper becomes useful when it helps you understand the document, connect it to what it belongs to and notice when something needs doing.")
replace(en, "KEEPER PRODUCT DIRECTION", "KEEPER")
replace(en, "Keeps the file.", "Stores the file.")
replace(en, "Processes the content.", "Reads it and pulls out the important parts.")
replace(en, "Recognition and extraction proposals help you start from something useful rather than from zero.", "The useful details can already be in front of you instead of staying buried in the document.")
replace(en, "Gives the document meaning and context.", "Helps show what the document belongs to.")
replace(en, "Type, category, related person, contract, asset or matter can become part of the structure.", "It can suggest a category and connect the document to the right person, contract, asset or matter.")
replace(en, "The date stays buried in the PDF.", "The deadline stays buried in the document.")
replace(en, "Surfaces a possible deadline.", "Can bring the deadline forward.")
replace(en, "The source can be reviewed, and reminders remain approval-first.", "You can check the original passage, and reminders only happen after you approve them.")
replace(en, "You search for a file.", "You have to remember where to look.")
replace(en, "You rely on filename, location or memory.", "You rely on the filename, folder or your memory of where you put it.")
replace(en, "The document content becomes searchable too.", "You can search by what is inside the document too.")
replace(en, "The aim is to stop requiring you to remember where you saved it.", "You do not necessarily need to remember the filename or where you saved it.")
replace(en, "The same Keeper work across very different documents.", "The same help, across very different documents.")
replace(en, "These are illustrative examples of the planned product experience, not real user data and not automatic decisions.", "A few everyday examples of the kind of admin Keeper can take off your hands.")
replace(en, "Do not make the user dig out the claim number and deadline.", "You should not have to hunt for the claim number and deadline yourself.")
replace(en, "An insurer sends a letter. On its own it is still just a PDF.", "An insurance letter comes in. Keeper can help bring the details you need for the claim straight to the surface.")
replace(en, "recognize the kind of document", "recognize that it may be an insurance document")
replace(en, "suggest the related claim or vehicle", "work out which claim or vehicle it may belong to")
replace(en, "flag when a reply or follow-up may be needed", "tell you when a reply or follow-up may be needed")
replace(en, "A deadline should not remain just another line in a document.", "A payment deadline should not disappear among the other lines.")
replace(en, "Keeper tries to turn the document into structured, reviewable information.", "With an invoice, it is not enough to have the file. You want the amount, due date and issuer at a glance.")
replace(en, "propose issuer, amount and date recognition", "pull out the issuer, amount and date")
replace(en, "suggest document type and category", "recognize that it may be an invoice or payment notice")
replace(en, "show where the deadline came from", "show where the deadline appears in the document")
replace(en, "propose a reminder that you approve", "suggest a reminder for you to approve")
replace(en, "Do not rely on memory to connect old and new documents.", "Let the new document find the old contract instead of relying on your memory.")
replace(en, "suggest relationships to earlier documents", "look for related earlier documents")
replace(en, "Turn mixed documents into a clearer administrative picture.", "Different documents, but all part of the same job.")
replace(en, "suggest a shared project or matter context", "work out which job or matter they may belong to")
replace(en, "help you return later without rebuilding the context", "help you pick up later where you left off")
replace(en, "Keeper helps. It does not decide for you.", "Keeper helps, but the final say stays with you.")
replace(en, "Important facts need a source.", "See where an important detail came from.")
replace(en, "The aim is to show what part of the document supports an extracted date or other important value.", "For an important date or amount, you should be able to go back to the part of the document Keeper read it from.")
replace(en, "Uncertainty should be visible.", "If Keeper is not sure, it should say so.")
replace(en, "If something is not reliable enough, Keeper should ask for review rather than pretend certainty.", "If something cannot be recognized confidently enough, Keeper should ask you to check it.")
replace(en, "Your correction comes first.", "If you correct it, that correction should stick.")
replace(en, "A later automatic proposal must not quietly overwrite a correction you already made.", "A later automatic suggestion should not quietly undo a correction you already made.")
replace(en, "AXIONA Keeper is in development and is not available for download yet. The first planned public release is through the Apple App Store. This page describes the intended product experience; it does not present the app as finished.", "AXIONA Keeper is in development and is not available to download yet. The first public release is planned for iPhone and iPad through the Apple App Store.")

replace("en/index.html", "You should not have to decode and organize every document by hand.", "Your time should not disappear into sorting documents.")
replace("en/index.html", "Bring in a PDF, image or photo. Keeper is designed to read it, recognize what kind of document it may be, surface important information, help classify and connect it to the right context, then flag when something may need your attention. Important decisions remain yours.", "Bring in a PDF or a photo of a document. Keeper reads it, tries to understand what it is, pulls out the important details, works out what it may belong to and tells you if something needs your attention. The decision stays with you.")
replace("en/index.html", "Recognizes and surfaces.", "Makes sense of it and pulls out what matters.")
replace("en/index.html", "Document type, key facts, dates and possible deadlines.", "A short summary, important details, dates and possible deadlines.")
replace("en/index.html", "Organizes it.", "Finds what it may belong to.")
replace("en/index.html", "Suggests category and relationships to the context the document belongs to.", "Suggests a link to the right person, contract, asset or matter.")
replace("en/index.html", "Flags when it may need action.", "Tells you when you may need to act.")
replace("en/index.html", "The next step remains a proposal for you to review and approve.", "If it finds a deadline or task, it tells you. You approve the next step.")
replace("en/index.html", "Less manual admin. Less uncertainty.", "Less searching. Less manual admin.")
replace("en/solutions.html", "A private document assistant designed to understand and organize documents, not merely store them.", "A private document assistant that does more than store files: it helps you understand what is in them, what they belong to and whether you need to do anything.")
replace("en/solutions.html", "Bring in the document. Keeper works on it.", "Bring in the document. Keeper works through it.")
replace("en/solutions.html", "The goal is to read the document, recognize its type, surface important facts and deadlines, suggest the right category and context, then show when something may need attention. It is designed to reduce manual admin rather than behave like another storage service.", "Keeper reads the document, tries to understand what it is, pulls out important details and deadlines, works out what it may belong to and tells you if something needs doing. The goal is simple: less time spent sorting and rereading documents by hand.")
replace("en/solutions.html", "processes document content locally", "works from the document content")
replace("en/solutions.html", "document-type and category proposals", "tries to recognize what kind of document it is")
replace("en/solutions.html", "suggests relationships and context", "finds what it may belong to")
replace("en/solutions.html", "when something may need review or action", "when something may need checking or doing")
replace("en/solutions.html", "You approve the important steps.", "The decision stays with you.")

# German Keeper — natural German rather than literal product-language translation.
de = "de/keeper.html"
replace(de, "Sie geben das Dokument hinein. Keeper übernimmt einen großen Teil der Verwaltungsarbeit darum.", "Sie fügen das Dokument hinzu. Keeper übernimmt einen großen Teil der Arbeit, die sonst daran hängen bleibt.")
replace(de, "Ein PDF, Bild oder Foto kommt herein. Keeper soll den Inhalt lesen, erkennen, um welche Art Dokument es sich handeln könnte, wichtige Angaben und Termine hervorheben und anschließend vorschlagen, wozu es gehört und ob etwas zu tun ist. Sie sollen nicht jede Datei erst vollständig lesen, benennen und manuell einsortieren müssen.", "Ob PDF oder Foto eines Dokuments: Keeper liest den Inhalt, versucht zu erkennen, worum es geht, fasst ihn kurz zusammen, hebt wichtige Angaben und Termine hervor und zeigt anschließend, wozu das Dokument gehören könnte und ob Sie etwas damit tun müssen. Sie sollen nicht jede Unterlage erst selbst vollständig lesen, benennen, sortieren und im Kopf behalten müssen.")
replace(de, "Keeper schlägt vor und bereitet vor. Unsichere Angaben können Sie prüfen; Schritte mit tatsächlichen Folgen bleiben unter Ihrer Freigabe.", "Wenn Keeper bei etwas unsicher ist, zeigt es das. Sie können korrigieren, und Erinnerungen oder andere nächste Schritte entstehen erst nach Ihrer Freigabe.")
replace(de, "Inhalt in nutzbaren Text umwandeln.", "Dokument lesen.")
replace(de, "Die Grundlage ist der Dokumentinhalt, nicht nur der Dateiname.", "Keeper arbeitet mit dem Inhalt, nicht nur mit dem Dateinamen.")
replace(de, "Vorschlagen, welche Dokumentart eingegangen ist.", "Versuchen zu erkennen, was eingegangen ist.")
replace(de, "Wichtige Verwaltungsdaten herausziehen.", "Kurz zusammenfassen und Wichtiges hervorheben.")
replace(de, "Datum, Betrag, Referenz, Absender oder Frist — sofern die Quelle dies trägt.", "Datum, Betrag, Referenz, Absender oder Frist — und, wo möglich, die Stelle im Dokument, aus der die Angabe stammt.")
replace(de, "Kategorie und Zusammenhang vorschlagen.", "Prüfen, wozu es gehören könnte.")
replace(de, "Zu welcher Person, welchem Anbieter, Vertrag, Gegenstand oder Vorgang das Dokument gehören könnte; unklare Zuordnungen bleiben prüfbar.", "Keeper kann eine Verbindung zu Person, Anbieter, Vertrag, Gegenstand oder Vorgang vorschlagen. Ist die Zuordnung unsicher, können Sie sie prüfen.")
replace(de, "Zeigen, wenn etwas Aufmerksamkeit braucht.", "Hinweisen, wenn etwas Ihre Aufmerksamkeit braucht.")
replace(de, "Eine mögliche Frist, unsichere Angabe oder ein nächster Schritt.", "Zum Beispiel eine Frist, eine unsichere Angabe oder ein möglicher nächster Schritt.")
replace(de, "Keeper führt keine folgenreichen Schritte unbemerkt im Hintergrund aus.", "Keeper kann den nächsten Schritt vorbereiten, entscheidet aber nicht für Sie.")
replace(de, "Erinnerungen und andere praktische Schritte benötigen Prüfung und Freigabe.", "Unsichere Angaben prüfen Sie selbst; Erinnerungen oder andere Schritte entstehen erst nach Ihrer Freigabe.")
replace(de, "Dass die Datei gespeichert ist, reicht nicht. Sie müssen auch verstehen, was darin steckt.", "Dass das Dokument gespeichert ist, reicht nicht. Sie möchten auch wissen, was darin steht und was damit zu tun ist.")
replace(de, "Ein digitales Archiv kann ein Dokument aufbewahren. Die eigentliche Verwaltung beginnt danach: verstehen, was eingegangen ist, wichtige Angaben herausziehen, den Zusammenhang erkennen und daran denken, ob etwas zu tun ist. Keeper soll Ihnen möglichst viel dieser Handarbeit abnehmen.", "Ein Speicher bewahrt die Datei auf. Lesen, wichtige Angaben finden, den Zusammenhang erkennen und Fristen im Kopf behalten müssen Sie trotzdem selbst. Genau von dieser Arbeit soll Keeper Ihnen möglichst viel abnehmen.")
replace(de, "Keeper kann eine Dokumentart vorschlagen, damit Sie sie nicht aus dem Dateinamen erraten müssen.", "Keeper versucht zu erkennen, ob zum Beispiel eine Rechnung, ein Vertrag, eine Mitteilung oder ein Schreiben eingegangen ist.")
replace(de, "Wichtige Angaben und Termine können hervorgehoben und wichtige Werte mit ihrer Quelle verbunden werden.", "Keeper fasst den Inhalt kurz zusammen, hebt wichtige Angaben und Termine hervor und kann zeigen, woher sie stammen.")
replace(de, "Keeper kann Kategorie und Beziehungen zu Person, Anbieter, Vertrag, Gegenstand oder Vorgang vorschlagen.", "Keeper kann vorschlagen, zu welcher Person, welchem Anbieter, Vertrag, Gegenstand oder Vorgang das Dokument gehört.")
replace(de, "Wenn eine Frist oder ein nächster Schritt erkannt wird, kann Keeper darauf gesondert hinweisen.", "Wenn Keeper eine Frist oder eine mögliche Aufgabe findet, weist es Sie darauf hin.")
replace(de, "Sie bringen das Dokument hinein. Keeper übernimmt den größten Teil der Verarbeitung.", "Sie fügen das Dokument hinzu. Keeper arbeitet es Schritt für Schritt durch.")
replace(de, "Der geplante Nutzerweg beginnt nicht mit dem Anlegen von Ordnern. Er beginnt mit einem Dokument, das Keeper Schritt für Schritt in nutzbare, prüfbare Verwaltungsinformation überführt.", "Sie müssen vorher weder Ordner noch Dateinamen festlegen. Fügen Sie das Dokument hinzu, und Keeper arbeitet es Schritt für Schritt durch.")
replace(de, "PDF, Bild, Foto oder geteiltes Dokument.", "PDF oder Foto eines Dokuments.")
replace(de, "02 / LOKALE OCR", "02 / TEXTERKENNUNG")
replace(de, "Text wird lokal extrahiert, damit die weitere Verarbeitung auf dem Inhalt und nicht nur auf dem Dateinamen basiert.", "Wo möglich, liest Keeper den Text auf Ihrem Gerät, damit es mit dem Dokument selbst und nicht nur mit dem Dateinamen arbeiten kann.")
replace(de, "03 / VERSTEHEN", "03 / EINORDNEN")
replace(de, "Verstehen, was eingegangen ist.", "Einordnen, um welche Art Dokument es sich handeln könnte.")
replace(de, "Keeper kann eine kurze verständliche Zusammenfassung erstellen und Dokumentart sowie Kategorie vorschlagen. Unsichere Ergebnisse bleiben zur Prüfung offen.", "Keeper kann den Inhalt kurz zusammenfassen und vorschlagen, welche Art Dokument es ist. Wenn etwas unsicher ist, zeigt es das.")
replace(de, "KEEPER: VERSTEHT UND FASST ZUSAMMEN", "KEEPER: ORDNET EIN UND FASST ZUSAMMEN")
replace(de, "Hervorheben, was zählt.", "Hervorheben, was Sie wissen sollten.")
replace(de, "Daten, Fristen, Beträge und andere relevante Werte können getrennt angezeigt werden; die Originalquelle bleibt prüfbar.", "Daten, Fristen, Beträge und andere wichtige Angaben können separat erscheinen. Das Originaldokument bleibt jederzeit einsehbar.")
replace(de, "KEEPER: HEBT ANGABEN UND QUELLE HERVOR", "KEEPER: HEBT WICHTIGE ANGABEN HERVOR")
replace(de, "Vorschlagen, wohin es gehört und womit es zusammenhängt.", "Den Platz zwischen den anderen Unterlagen finden.")
replace(de, "Ziel ist nicht ein starres Ordnersystem, sondern der richtige Kontext: Person, Anbieter, Vertrag, Gegenstand oder Vorgang. Automatische Vorschläge bleiben änderbar und umkehrbar.", "Keeper kann eine Kategorie und eine Verbindung zu Person, Anbieter, Vertrag, Gegenstand oder Vorgang vorschlagen. Den Vorschlag können Sie jederzeit ändern.")
replace(de, "KEEPER: SCHLÄGT ZUORDNUNG UND KONTEXT VOR", "KEEPER: FINDET, WOZU ES GEHÖREN KÖNNTE")
replace(de, "Zeigen, wenn Handlungsbedarf bestehen könnte.", "Hinweisen, wenn etwas ansteht.")
replace(de, "Frist, Wartezustand oder Aufgabe können als Vorschlag erscheinen. Eine Erinnerung entsteht erst nach Ihrer Freigabe.", "Findet Keeper eine Frist oder eine mögliche Aufgabe, weist es Sie darauf hin. Eine Erinnerung entsteht erst nach Ihrer Freigabe.")
replace(de, "Speichern ist nicht der Kern des Produkts.", "Keeper soll mehr können als Dateien speichern.")
replace(de, "Die Datei aufzubewahren ist nur die Grundlage. Keeper wird dort wertvoll, wo aus einem Dokument verständliche, durchsuchbare und nutzbare Verwaltungsinformation wird.", "Speichern ist nur der erste Schritt. Keeper wird dann hilfreich, wenn es das Dokument verständlicher macht, den Zusammenhang findet und Sie rechtzeitig auf Aufgaben hinweist.")
replace(de, "KEEPER PRODUKTRICHTUNG", "KEEPER")
replace(de, "Verarbeitet den Inhalt.", "Liest den Inhalt und hebt Wichtiges hervor.")
replace(de, "Erkennungs- und Extraktionsvorschläge geben Ihnen einen brauchbaren Ausgangspunkt.", "Wichtige Angaben können bereits sichtbar sein, statt im Dokument verborgen zu bleiben.")
replace(de, "Gibt dem Dokument Bedeutung und Kontext.", "Hilft zu erkennen, wozu das Dokument gehört.")
replace(de, "Dokumentart, Kategorie und Bezug zu Person, Vertrag, Gegenstand oder Vorgang können Teil der Struktur werden.", "Keeper kann eine Kategorie vorschlagen und das Dokument mit Person, Vertrag, Gegenstand oder Vorgang verknüpfen.")
replace(de, "Das wichtige Datum bleibt im PDF verborgen.", "Die Frist bleibt im Dokument verborgen.")
replace(de, "Hebt eine mögliche Frist hervor.", "Kann die Frist hervorheben.")
replace(de, "Die Quelle bleibt prüfbar; Erinnerungen bleiben freigabepflichtig.", "Die ursprüngliche Stelle bleibt einsehbar; eine Erinnerung entsteht erst nach Ihrer Freigabe.")
replace(de, "Sie suchen eine Datei.", "Sie müssen wissen, wo Sie suchen sollen.")
replace(de, "Sie verlassen sich auf Dateiname, Speicherort oder Erinnerung.", "Sie verlassen sich auf Dateiname, Ordner oder Ihre Erinnerung daran, wo Sie die Datei abgelegt haben.")
replace(de, "Auch der Dokumentinhalt wird auffindbar.", "Sie können auch nach dem Inhalt suchen.")
replace(de, "Ziel ist, dass Sie später nicht mehr wissen müssen, wo Sie etwas abgelegt haben.", "So müssen Sie später nicht unbedingt wissen, wie die Datei heißt oder wo Sie sie abgelegt haben.")
replace(de, "Die gleiche Keeper-Arbeit bei ganz unterschiedlichen Dokumenten.", "Die gleiche Hilfe bei ganz unterschiedlichen Dokumenten.")
replace(de, "Die folgenden Beispiele veranschaulichen die geplante Produktfunktion. Es sind keine echten Nutzerdaten und keine automatischen Entscheidungen.", "Einige alltägliche Beispiele dafür, welche Arbeit Keeper Ihnen abnehmen kann.")
replace(de, "Nicht selbst Aktenzeichen und Frist aus dem Schreiben herausziehen müssen.", "Aktenzeichen und Frist nicht selbst im Schreiben suchen müssen.")
replace(de, "Ein Schreiben der Versicherung kommt an. Zunächst ist es nur eine PDF-Datei.", "Ein Versicherungsschreiben kommt an. Keeper kann die Angaben hervorheben, die Sie für die weitere Bearbeitung brauchen.")
replace(de, "Art des Dokuments erkennen", "erkennen, dass es sich um ein Versicherungsdokument handeln könnte")
replace(de, "zugehörigen Schadenfall oder Fahrzeug vorschlagen", "prüfen, zu welchem Schadenfall oder Fahrzeug es gehören könnte")
replace(de, "auf mögliche Antwort oder Nachverfolgung hinweisen", "darauf hinweisen, wenn eine Antwort oder spätere Nachfrage nötig sein könnte")
replace(de, "Eine Frist soll nicht nur eine Zeile im Dokument bleiben.", "Die Zahlungsfrist soll nicht zwischen anderen Zeilen untergehen.")
replace(de, "Keeper versucht, aus dem Dokument strukturierte, prüfbare Information zu machen.", "Bei einer Rechnung möchten Sie Betrag, Fälligkeit und Absender auf einen Blick sehen — nicht nur die Datei besitzen.")
replace(de, "Absender, Betrag und Datum als Kandidaten erkennen", "Absender, Betrag und Datum hervorheben")
replace(de, "Dokumentart und Kategorie vorschlagen", "erkennen, dass es sich um eine Rechnung oder Zahlungsmitteilung handeln könnte")
replace(de, "Quelle der Frist sichtbar machen", "zeigen, wo die Frist im Dokument steht")
replace(de, "Erinnerung vorschlagen, die Sie freigeben", "eine Erinnerung vorschlagen, die Sie freigeben")
replace(de, "Alte und neue Unterlagen nicht im Kopf zusammenführen müssen.", "Neue Unterlagen sollen den alten Vertrag finden — nicht Ihre Erinnerung.")
replace(de, "Beziehungen zu früheren Dokumenten vorschlagen", "nach passenden früheren Dokumenten suchen")
replace(de, "Aus verschiedenen Unterlagen ein verständlicheres Verwaltungsbild machen.", "Verschiedene Unterlagen, aber sie gehören zur gleichen Arbeit.")
replace(de, "gemeinsamen Projekt- oder Vorgangskontext vorschlagen", "prüfen, zu welcher Arbeit oder welchem Vorgang sie gehören könnten")
replace(de, "später im vorhandenen Kontext weiterarbeiten helfen", "später dort weitermachen helfen, wo Sie aufgehört haben")
replace(de, "Keeper hilft. Entscheiden tun Sie.", "Keeper hilft, aber das letzte Wort haben Sie.")
replace(de, "Wichtige Angaben brauchen eine Quelle.", "Sie sehen, woher eine wichtige Angabe stammt.")
replace(de, "Ziel ist, sichtbar zu machen, welcher Teil des Dokuments ein extrahiertes Datum oder einen anderen wichtigen Wert stützt.", "Bei einem wichtigen Datum oder Betrag sollen Sie zu der Stelle zurückgehen können, aus der Keeper die Angabe gelesen hat.")
replace(de, "Unsicherheit muss sichtbar bleiben.", "Wenn Keeper unsicher ist, soll es das sagen.")
replace(de, "Wenn etwas nicht zuverlässig genug ist, soll Keeper eine Prüfung verlangen statt Sicherheit vorzutäuschen.", "Wenn etwas nicht sicher genug erkannt wird, soll Keeper Sie um eine Prüfung bitten.")
replace(de, "Ihre Korrektur hat Vorrang.", "Wenn Sie etwas korrigieren, soll diese Korrektur bleiben.")
replace(de, "Ein späterer automatischer Vorschlag darf Ihre Korrektur nicht still überschreiben.", "Ein späterer automatischer Vorschlag soll Ihre Korrektur nicht unbemerkt wieder ändern.")
replace(de, "AXIONA Keeper befindet sich in Entwicklung und steht noch nicht zum Download bereit. Die erste geplante öffentliche Veröffentlichung erfolgt über den Apple App Store. Diese Seite beschreibt das geplante Produkterlebnis und stellt die App nicht als fertig dar.", "AXIONA Keeper befindet sich in Entwicklung und steht noch nicht zum Download bereit. Die erste öffentliche Version ist für iPhone und iPad über den Apple App Store geplant.")

replace("de/index.html", "Sie sollten nicht jedes Dokument selbst lesen, verstehen und manuell einsortieren müssen.", "Ihre Zeit sollte nicht für das Sortieren von Unterlagen draufgehen.")
replace("de/index.html", "Sie bringen ein PDF, Bild oder Foto hinein. Keeper soll den Inhalt lesen, die Dokumentart erkennen, wichtige Angaben hervorheben, bei Zuordnung und Zusammenhang helfen und zeigen, wenn etwas Aufmerksamkeit braucht. Wichtige Entscheidungen bleiben bei Ihnen.", "Sie fügen ein PDF oder ein Foto eines Dokuments hinzu. Keeper liest den Inhalt, versucht zu erkennen, worum es geht, hebt wichtige Angaben hervor, sucht den passenden Zusammenhang und weist Sie darauf hin, wenn etwas zu tun ist. Die Entscheidung bleibt bei Ihnen.")
replace("de/index.html", "Erkennen und hervorheben.", "Einordnen und Wichtiges hervorheben.")
replace("de/index.html", "Dokumentart, wichtige Angaben, Termine und mögliche Fristen.", "Kurze Zusammenfassung, wichtige Angaben, Termine und mögliche Fristen.")
replace("de/index.html", "Ordnen.", "Finden, wozu es gehört.")
replace("de/index.html", "Kategorie und Beziehungen zum passenden Kontext vorschlagen.", "Eine Verbindung zu Person, Vertrag, Gegenstand oder Vorgang vorschlagen.")
replace("de/index.html", "Handlungsbedarf sichtbar machen.", "Hinweisen, wenn etwas zu tun ist.")
replace("de/index.html", "Der nächste Schritt bleibt ein Vorschlag, den Sie prüfen und freigeben.", "Findet Keeper eine Frist oder Aufgabe, weist es Sie darauf hin. Den nächsten Schritt geben Sie frei.")
replace("de/index.html", "Weniger manuelle Verwaltung. Weniger Unsicherheit.", "Weniger Suchen. Weniger manuelle Verwaltung.")
replace("de/solutions.html", "Ein privater Dokumentenassistent, der Unterlagen verstehen und einordnen soll — nicht nur speichern.", "Ein privater Dokumentenassistent, der mehr kann als Dateien speichern: Er hilft zu verstehen, was darin steht, wozu es gehört und ob etwas zu tun ist.")
replace("de/solutions.html", "Dokument hinein. Keeper arbeitet damit.", "Dokument hinzufügen. Keeper arbeitet es durch.")
replace("de/solutions.html", "Ziel ist, das Dokument zu lesen, die Art zu erkennen, wichtige Angaben und Fristen hervorzuheben, Kategorie und Kontext vorzuschlagen und zu zeigen, wenn etwas Aufmerksamkeit braucht. Keeper soll manuelle Verwaltung reduzieren, statt nur ein weiterer Speicherort zu sein.", "Keeper liest das Dokument, versucht zu erkennen, worum es geht, hebt wichtige Angaben und Fristen hervor, sucht den passenden Zusammenhang und weist Sie darauf hin, wenn etwas zu tun ist. Ziel ist einfach: weniger Zeit für manuelles Sortieren und erneutes Lesen.")
replace("de/solutions.html", "Dokumentinhalt lokal verarbeiten", "mit dem Dokumentinhalt arbeiten")
replace("de/solutions.html", "Dokumentart und Kategorie vorschlagen", "versuchen zu erkennen, welche Art Dokument es ist")
replace("de/solutions.html", "Beziehungen und Kontext vorschlagen", "finden, wozu es gehören könnte")
replace("de/solutions.html", "wenn Prüfung oder Handlung nötig sein könnte", "wenn etwas geprüft oder erledigt werden muss")
replace("de/solutions.html", "Wichtige Schritte geben Sie frei.", "Die Entscheidung bleibt bei Ihnen.")

# Make live verification prove the R97 human-copy release rather than stale R96 phrases.
wf = ".github/workflows/axiona-pages-rebuild.yml"
replace(wf, "Verify live social previews and Keeper R96 intelligence story", "Verify live social previews and Keeper R97 human copy")
replace(wf, "elvégzi körülötte az adminisztráció nagy részét", "elvégzi a vele járó adminisztráció nagy részét")
replace(wf, "does most of the admin work around it", "takes care of much of the admin around it")
replace(wf, "übernimmt einen großen Teil der Verwaltungsarbeit darum", "übernimmt einen großen Teil der Arbeit, die sonst daran hängen bleibt")
replace(wf, '"keeper_story": "R96"', '"keeper_story": "R97"')

# Add regression checks for the exact copy problems found in this review.
q = "scripts/verify_public_quality.py"
p = ROOT / q
text = p.read_text(encoding="utf-8")
needle = 'KEEPER_PLATFORM_MARKERS = ("iPhone", "iPad", "Apple App Store")\n'
if needle not in text:
    raise SystemExit("quality marker insertion point missing")
addition = '''KEEPER_HUMAN_COPY_FORBIDDEN = {\n    "": (\n        "PDF, kép vagy fotó",\n        "strukturált, ellenőrizhető adatot",\n        "KEEPER FEJLESZTÉSI IRÁNY",\n        "tervezett termékműködés szemléltető példái",\n    ),\n    "en/": (\n        "PDF, image or photo",\n        "structured, reviewable information",\n        "KEEPER PRODUCT DIRECTION",\n        "illustrative examples of the planned product experience",\n    ),\n    "de/": (\n        "PDF, Bild oder Foto",\n        "strukturierte, prüfbare Information",\n        "KEEPER PRODUKTRICHTUNG",\n        "veranschaulichen die geplante Produktfunktion",\n    ),\n}\n'''
text = text.replace(needle, needle + addition, 1)
needle2 = '        for marker in KEEPER_PLATFORM_MARKERS:\n            if marker not in keeper_text:\n                errors.append(f"Keeper platform marker missing in {keeper}: {marker}")\n'
if needle2 not in text:
    raise SystemExit("quality checker insertion point missing")
addition2 = '''        for forbidden in KEEPER_HUMAN_COPY_FORBIDDEN[prefix]:\n            if forbidden in keeper_text:\n                errors.append(f"Keeper human-copy regression in {keeper}: {forbidden}")\n'''
text = text.replace(needle2, needle2 + addition2, 1)
p.write_text(text, encoding="utf-8")

print("OK_KEEPER_HUMAN_COPY_R97_PATCHED")
